# Generated by Django 3.2 on 2021-04-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='conditie',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
